[2025-10-03T12:58:04.279+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-03T12:58:04.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_four.create_table_task scheduled__2025-10-03T12:56:00+00:00 [queued]>
[2025-10-03T12:58:04.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_four.create_table_task scheduled__2025-10-03T12:56:00+00:00 [queued]>
[2025-10-03T12:58:04.335+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-10-03T12:58:04.472+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): create_table_task> on 2025-10-03 12:56:00+00:00
[2025-10-03T12:58:04.486+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=580) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-03T12:58:04.490+0000] {standard_task_runner.py:63} INFO - Started process 587 to run task
[2025-10-03T12:58:04.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_four', 'create_table_task', 'scheduled__2025-10-03T12:56:00+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/dag_four.py', '--cfg-path', '/tmp/tmp4foob114']
[2025-10-03T12:58:04.509+0000] {standard_task_runner.py:91} INFO - Job 144: Subtask create_table_task
[2025-10-03T12:58:04.552+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2025-10-03T12:58:04.647+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_four.create_table_task scheduled__2025-10-03T12:56:00+00:00 [running]> on host 7aff8d0a020c
[2025-10-03T12:58:05.129+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_four' AIRFLOW_CTX_TASK_ID='create_table_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-03T12:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-03T12:56:00+00:00'
[2025-10-03T12:58:05.135+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-03T12:58:05.137+0000] {sql.py:276} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS my_table (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        
[2025-10-03T12:58:05.185+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-10-03T12:58:05.219+0000] {base.py:84} INFO - Using connection ID 'postgres_conn' for task execution.
[2025-10-03T12:58:05.235+0000] {sql.py:487} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS my_table (
            id SERIAL PRIMARY KEY,
            name VARCHAR(50),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
        , parameters: None
[2025-10-03T12:58:05.250+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-03T12:58:05.275+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_four, task_id=create_table_task, run_id=scheduled__2025-10-03T12:56:00+00:00, execution_date=20251003T125600, start_date=20251003T125804, end_date=20251003T125805
[2025-10-03T12:58:05.342+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-10-03T12:58:05.372+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
